kitti_to_ros2bag_node:
  ros__parameters:
    kitti_path: "/data/kitti/raw/2011_09_29_drive_0071_sync/"
    # this folder shall have image_00, image_01, image_02, image_03, oxts, and velodyne_points
    calib_folder: "2011_09_29_calib"
    # i.e. kitti_path/calib_folder. This folder shall have
    # calib_cam_to_cam.txt, calib_imu_to_velo.txt, and calib_velo_to_cam.txt
    # if not, the camera_info won't be outputed
    dirs: ["image_00", "image_01", "image_02", "image_03", "oxts", "velodyne_points"] # dirs that you want to publish
    # dirs: ["image_00"] this will output image_00 data only
    output_bag_name: "2011_09_29_drive_0071_sync_bag"
